export const testPlayerTanks = [
	{
		id: 84,
		type: 'ЛТ',
		image: '/media/tanks/98/tank_card_line_KV-2.png',
		sprite: '/media/tanks/97/game_tank_lttb_rUMt47K.png',
		hull_sprite: '/media/tanks/97/game_tank_lttb_dead_L1hW3Os.png',
		name: 'LTTB',
		hp: 50,
		moving_price: 1,
		damage_bonus: 5,
		critical_chance: 5,
		overlook: 5,
		armor: 50,
		block_chance: 1,
		level: 1,
		owner: 3,
	},
	{
		id: 85,
		type: 'САУ',
		image: '/media/tanks/98/tank_card_line_KV-2.png',
		sprite: '/media/tanks/95/game_tank_Hummel_hH4pFP8.png',
		hull_sprite: '/media/tanks/95/game_tank_Hummel_dead_uWt9irj.png',
		name: 'Hummel',
		hp: 50,
		moving_price: 2,
		damage_bonus: 5,
		critical_chance: 1,
		overlook: 2,
		armor: 10,
		block_chance: 1,
		level: 1,
		owner: 3,
	},
	{
		id: 86,
		type: 'HT',
		image: '/media/tanks/98/tank_card_line_KV-2.png',
		sprite: '/media/tanks/96/game_tank_O-I_WrztvNA.png',
		hull_sprite: '/media/tanks/96/game_tank_O-I_dead_tCKVllb.png',
		name: 'O-I',
		hp: 50,
		moving_price: 4,
		damage_bonus: 5,
		critical_chance: 1,
		overlook: 4,
		armor: 30,
		block_chance: 1,
		level: 1,
		owner: 3,
	},
];
export const testPlayers = [
	{ username: 'testUser', tanks: testPlayerTanks },
	{ username: 'botUser', tanks: testPlayerTanks },
	{ username: 'botUser2', tanks: testPlayerTanks },
	{ username: 'botUser3', tanks: testPlayerTanks },
];
